name = "rest-express-worker"
main = "dist/index.js"
compatibility_date = "2024-05-01"

# The 'type = "javascript"' setting is optional but can be explicitly set
# if you are deploying a simple, built Worker file.

# --- Optional: For Cloudflare Pages Deployments ---
# If you are deploying this as a Cloudflare Pages project with a Function, 
# you should also include the `site` block to tell Pages where your 
# static assets are located (from your Vite build).

[site]
bucket = "dist/public"
# This path matches the output of your Vite build: "../dist/public/..."
